//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillManager.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.PayOptions = new HashSet<PayOption>();
        }
    
        public int BillId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int AccountId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<PayOption> PayOptions { get; set; }
        public virtual Category Category { get; set; }
    }
}
