//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirst1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteLink
    {
        public int FavoriteLinkId { get; set; }
        public string Label { get; set; }
        public int AccountId { get; set; }
    
        public virtual Website Website { get; set; }
    }
}
