//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirst1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayOption
    {
        public int PayOptionId { get; set; }
        public string Label { get; set; }
        public bool IsPrimary { get; set; }
        public int WebsiteWebsiteId { get; set; }
        public int BillId { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
